### PR TITLE
Sentry Integration

### PR DESCRIPTION
**Pull request by Aminehassou**
This PR implements sentry for the react app. It also adds new information to the readme file regarding how to setup sentry both locally and in production.

### CODE REVIEW

**Comment by mattfordham** [comment]
@ragesoss @Aminehassou The server is using Yarn, as am I (although it's possible I previously accidentally added and then removed a package-lock.json file). Let's delete package-lock.json and also add to the gitignore, just in case. Thanks!

**Comment by Aminehassou** [comment]
Ok, I removed the package-lock file and added it to .gitignore

**Comment by ragesoss** [comment]
The yarn.lock file is also getting a lot smaller. Is that expected for this change, @Aminehassou ?

**Comment by Aminehassou** [comment]
Looks like it was an issue with npm, I rolled back the changes i made then reinstalled with yarn. the yarn.lock file seems to have the correct size now. The checksums in the lock file seem to have changed though, could be due to me having a different yarn version? It's unclear since we don't have a specific yarn version specified in the docs. @ragesoss

**Comment by mattfordham** [comment]
@Aminehassou @ragesoss Coincidentally, I've specified a yarn version in another branch I'm working on and am almost ready to merge. SO, why don't we move forward with this PR and when I merge into master I'll make sure the specific version gets in there.

**Comment by ragesoss** [comment]
I've added .env.production to the `shared/config` directory in production, but I guess that's probably not the right place to put it. Since we deploy with Capistrano, I'm not sure how best to handle making it appear to live in the project's root directory. I think we could just check in `.env.production` with the Sentry DSN included, as it will be available client-side to anyone using the site anyway. I think the Sentry DSN is not considered a secret, and we can restrict submission of data via that DSN by specifying the allowed domain on the Sentry server side of things.

**Comment by mattfordham** [comment]
@ragesoss You could also put it in the encrypted production.yml.enc in the repo... that might be a good place for it.  You'd need the key though, which you could grab from the server.

https://guides.rubyonrails.org/security.html#custom-credentials

**Pull request merged**
